language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
install:
    - travis_retry composer install --no-interaction
script:
    - ./vendor/bin/phpcs --standard=psr2 src/
    - ./vendor/bin/phpunit --coverage-text
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
